# Generated by Django 5.2.6 on 2025-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Adınız Soyadınız', max_length=100, verbose_name='Ad Soyad')),
                ('subtitle', models.CharField(default='Web Geliştirici', max_length=200, verbose_name='Alt Başlık (Ünvan)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='portfolio/avatar/', verbose_name='Profil Fotoğrafı')),
                ('about_title', models.CharField(default='Hakkımda', max_length=100, verbose_name='Hakkımda Başlığı')),
                ('about_text', models.CharField(default='Buraya kendinizi tanıtan yazıyı girin...', verbose_name='Hakkımda Yazısı')),
            ],
            options={
                'verbose_name': 'Kişisel Bilgiler',
                'verbose_name_plural': 'Kişisel Bilgiler',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/', verbose_name='Proje Görseli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Proje Başlığı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='Proje Linki'),
        ),
    ]
