# Generated by Django 5.2.6 on 2025-12-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_text',
            field=models.TextField(default='Buraya kendinizi tanıtan yazıyı girin...', verbose_name='Hakkımda Yazısı'),
        ),
    ]
