# Generated by Django 5.2.6 on 2025-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_text',
            field=models.TextField(default='', verbose_name='Hakkımda Yazısı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_title',
            field=models.CharField(default='', max_length=100, verbose_name='Hakkımda Başlığı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Alt Başlık (Ünvan)'),
        ),
    ]
