# Generated by Django 5.2.6 on 2025-12-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
